version: '2'
services:
  fake-cms-mysql:
    restart: unless-stopped
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: Horaoen@624
      MYSQL_DATABASE: lin-cms
    ports:
      - "3306:3306"
    volumes:
      - "fake-cms-data-mysql:/var/mysqldb"
    command: --default-authentication-plugin=mysql_native_password

  main-server:
    depends_on:
      - fake-cms-mysql
    build:
      context: .
      dockerfile: Dockerfile
    image: fake-cms-springboot:latest
    ports:
      - "5001:5001"

volumes:
  fake-cms-data-mysql: