#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: Horaoen@624
    url: jdbc:mysql://42.192.5.249:3306/lin-cms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  type-aliases-package: com.example.myfirstcms.pojo
## 开启权限拦截
#auth:
#  enabled: true
#
## 开启登录要求验证码
#login-captcha:
#  enabled: true
#  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"
#
## 开启http请求日志记录
#request-log:
#  enabled: true
#
#
#logging:
#  level:
#    # web信息日志记录
#    web: debug
#    # SQL日志记录
#    io.github.talelin.latticy.mapper: debug




