#主配置文件

spring:
  # 激活环境配置
  profiles:
    active: dev
    # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: scy464658
    url: jdbc:mysql://localhost:3306/lin-cms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭默认静态资源的映射规则
      add-mappings: false