#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: Horaoen@624
    url: jdbc:mysql://42.192.5.249:3306/lin-cms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver

#properties文件格式：

mybatis-plus:
  type-aliases-package: com.example.myfirstcms.pojo


springdoc:
  packages-to-scan: com.example.myfirstcms.controller



